version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:22.14.0
    steps:
      - checkout
      
      - run:
          name: Install pnpm
          command: sudo npm install -g pnpm

      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile

      - run:
          name: Run Linter
          command: pnpm lint
          
      - run:
          name: Build Application
          command: pnpm build
          environment:
            VITE_MAPBOX_ACCESS_TOKEN: $VITE_MAPBOX_ACCESS_TOKEN
            VITE_GEMINI_API_KEY: $VITE_GEMINI_API_KEY
            VITE_GEMINI_MODEL_NAME: $VITE_GEMINI_MODEL_NAME
            VITE_SUPABASE_URL: $VITE_SUPABASE_URL
            VITE_SUPABASE_PUBLISHABLE_KEY: $VITE_SUPABASE_PUBLISHABLE_KEY
            VITE_ALLOWED_EMAIL: $VITE_ALLOWED_EMAIL
            VITE_RESUME_URL: $VITE_RESUME_URL

workflows:
  check_and_build:
    jobs:
      - build_and_test
