// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dasjvafuudjotbaoawrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhc2p2YWZ1dWRqb3RiYW9hd3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDc0MDYsImV4cCI6MjA3MDA4MzQwNn0.ti3wfv7-sz5jRDsLH4MYvEkXToRIv_rzIxMnCKuKsqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);